// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV00hkie_DZYVIe3H3VrtDvueNOsp4mM4',
    appId: '1:727207966559:web:8d60822c1bc6a62be868ea',
    messagingSenderId: '727207966559',
    projectId: 'fitdex-d7ad0',
    authDomain: 'fitdex-d7ad0.firebaseapp.com',
    storageBucket: 'fitdex-d7ad0.firebasestorage.app',
    measurementId: 'G-LWMN7R43MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfauMJsCmKRQKfs6WQwCvzODSTKAkJ_R4',
    appId: '1:727207966559:android:0c98b8c1ce7bdbe9e868ea',
    messagingSenderId: '727207966559',
    projectId: 'fitdex-d7ad0',
    storageBucket: 'fitdex-d7ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiq1Er9RGqvq3w7z8wQ5lu0y8sZ7neFPQ',
    appId: '1:727207966559:ios:50cb1fbf0ebe677de868ea',
    messagingSenderId: '727207966559',
    projectId: 'fitdex-d7ad0',
    storageBucket: 'fitdex-d7ad0.firebasestorage.app',
    iosBundleId: 'com.example.gymWorkoutFinderTrackerAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiq1Er9RGqvq3w7z8wQ5lu0y8sZ7neFPQ',
    appId: '1:727207966559:ios:50cb1fbf0ebe677de868ea',
    messagingSenderId: '727207966559',
    projectId: 'fitdex-d7ad0',
    storageBucket: 'fitdex-d7ad0.firebasestorage.app',
    iosBundleId: 'com.example.gymWorkoutFinderTrackerAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV00hkie_DZYVIe3H3VrtDvueNOsp4mM4',
    appId: '1:727207966559:web:26352b31d7b0a7a9e868ea',
    messagingSenderId: '727207966559',
    projectId: 'fitdex-d7ad0',
    authDomain: 'fitdex-d7ad0.firebaseapp.com',
    storageBucket: 'fitdex-d7ad0.firebasestorage.app',
    measurementId: 'G-FEL256FD9W',
  );
}
